#' Import an OpenClinica SAS Data and Syntax export
#'
#' Imports an OpenClinica SAS Data and Syntax export consisting of
#' `SAS_DATA.xml`, `SAS_MAP.xml`, and optionally `SAS_FORMAT.sas`.
#'
#' The SAS XMLMap is used to reconstruct the exported datasets, determine
#' variable names and data types, and locate the corresponding values in
#' `SAS_DATA.xml`. If `SAS_FORMAT.sas` is available, SAS value labels can
#' additionally be applied.
#'
#' Optionally, OpenClinica-generated table and variable names can be cleaned
#' by removing leading underscores and trailing numeric identifiers.
#'
#' @param path Character scalar. Path to the directory containing the
#'   OpenClinica SAS export files.
#' @param apply_formats Logical. If `TRUE`, apply SAS value labels from
#'   `SAS_FORMAT.sas` when the file exists.
#' @param clean_names Logical. If `TRUE`, remove leading underscores and
#'   autogenerated trailing numeric identifiers from imported table and
#'   variable names. A mapping between original and cleaned names is retained
#'   in the returned `name_map` component.
#' @param date_formats Character vector containing date formats to try when
#'   converting XML date values to R `Date` objects.
#' @param verbose Logical. If `TRUE`, print a short import summary.
#'
#' @return A list with components:
#' \describe{
#'   \item{typed}{Imported datasets with original coded values and appropriate
#'     R data types applied.}
#'   \item{display}{Imported datasets with SAS value labels applied where
#'     available.}
#'   \item{metadata}{Variable metadata extracted from `SAS_MAP.xml`.}
#'   \item{name_map}{Mappings between original OpenClinica names and cleaned
#'     table and variable names.}
#'   \item{formats}{Parsed SAS format assignments and value definitions from
#'     `SAS_FORMAT.sas`.}
#'   \item{checks}{Validation information for the import.}
#' }
#'
#' @export

import_sas_xml <- function(
    path,
    apply_formats = TRUE,
    clean_names = FALSE,
    date_formats = c("%Y-%m-%d", "%d.%m.%Y", "%Y/%m/%d"),
    verbose = TRUE
) {
  data_file <- file.path(path, "SAS_DATA.xml")
  map_file <- file.path(path, "SAS_MAP.xml")
  format_file <- file.path(path, "SAS_FORMAT.sas")
  
  if (!file.exists(data_file)) {
    stop("SAS_DATA.xml was not found in: ", path)
  }
  
  if (!file.exists(map_file)) {
    stop("SAS_MAP.xml was not found in: ", path)
  }
  
  if (apply_formats && !file.exists(format_file)) {
    warning(
      "SAS_FORMAT.sas was not found. ",
      "The data will be imported without SAS value labels.",
      call. = FALSE
    )
    apply_formats <- FALSE
  }
  
  data_xml <- xml2::read_xml(data_file)
  map_xml <- xml2::read_xml(map_file)
  # Each TABLE node in the XMLMap describes one SAS dataset
  tables <- xml2::xml_find_all(map_xml, ".//TABLE")

  if (length(tables) == 0L) {
    stop("No TABLE definitions were found in SAS_MAP.xml.")
  }
  
  metadata <- .extract_xml_metadata(tables)
  
  table_names <- vapply(tables, .get_table_name, character(1))
  raw_tables <- lapply(tables, .read_xml_table, data_xml = data_xml)
  names(raw_tables) <- table_names
  
  typed_tables <- lapply(
    names(raw_tables),
    function(table_name) {
      .convert_table_types(
        df = raw_tables[[table_name]],
        table_name = table_name,
        metadata = metadata,
        date_formats = date_formats
      )
    }
  )
  
  names(typed_tables) <- names(raw_tables)
  
  conversion <- .check_type_conversion(
    raw_tables = raw_tables,
    typed_tables = typed_tables,
    metadata = metadata
  )
  
  
  display_tables <- typed_tables
  format_map <- NULL
  format_values <- NULL
  format_coverage <- NULL
  
  if (apply_formats) {
    formats <- .read_sas_formats(format_file)
    format_map <- formats$assignments
    format_values <- formats$values
    
    formatted <- .apply_sas_formats(
      typed_tables = typed_tables,
      format_map = format_map,
      format_values = format_values
    )
    
    display_tables <- formatted$data
    format_coverage <- formatted$coverage
  }
  
  
  
  name_map <- .create_name_map(typed_tables)
  
  if (clean_names) {
    typed_tables <- .apply_clean_names(typed_tables, name_map)
    display_tables <- .apply_clean_names(display_tables, name_map)
    
    table_idx <- match(metadata$table, name_map$tables$original)
    metadata$table <- name_map$tables$clean[table_idx]
    
    column_key <- paste(
      name_map$columns$table_original,
      name_map$columns$column_original,
      sep = "\r"
    )
    
    metadata_key <- paste(
      name_map$columns$table_original[
        match(metadata$table, name_map$tables$clean)
      ],
      metadata$column,
      sep = "\r"
    )
    
    column_idx <- match(metadata_key, column_key)
    metadata$column <- name_map$columns$column_clean[column_idx]
    
    
    conversion_table_idx <- match(
      conversion$all$table,
      name_map$tables$original
    )
    
    conversion_column_key <- paste(
      conversion$all$table,
      conversion$all$variable,
      sep = "\r"
    )
    
    conversion_map_key <- paste(
      name_map$columns$table_original,
      name_map$columns$column_original,
      sep = "\r"
    )
    
    conversion_column_idx <- match(
      conversion_column_key,
      conversion_map_key
    )
    
    conversion$all$table <- name_map$tables$clean[conversion_table_idx]
    conversion$all$variable <- name_map$columns$column_clean[
      conversion_column_idx
    ]
    
    conversion$problems <- conversion$all[
      !is.na(conversion$all$datatype) &
        tolower(conversion$all$datatype) != "string" &
        conversion$all$newly_NA > 0L,
      ,
      drop = FALSE
    ]
    
    
    if (!is.null(format_map)) {
      format_table_original <- format_map$table
      format_table_idx <- match(
        format_table_original,
        name_map$tables$original
      )
      
      format_column_key <- paste(
        format_table_original,
        format_map$variable,
        sep = "\r"
      )
      
      format_map_key <- paste(
        name_map$columns$table_original,
        name_map$columns$column_original,
        sep = "\r"
      )
      
      format_column_idx <- match(format_column_key, format_map_key)
      valid_table <- !is.na(format_table_idx)
      
      format_map$table[valid_table] <- name_map$tables$clean[
        format_table_idx[valid_table]
      ]
      
      valid_column <- !is.na(format_column_idx)
      format_map$variable[valid_column] <- name_map$columns$column_clean[
        format_column_idx[valid_column]
      ]
    }
    
    if (!is.null(format_coverage)) {
      coverage_table_original <- format_coverage$table
      coverage_table_idx <- match(
        coverage_table_original,
        name_map$tables$original
      )
      
      coverage_column_key <- paste(
        coverage_table_original,
        format_coverage$variable,
        sep = "\r"
      )
      
      coverage_map_key <- paste(
        name_map$columns$table_original,
        name_map$columns$column_original,
        sep = "\r"
      )
      
      coverage_column_idx <- match(coverage_column_key, coverage_map_key)
      valid_table <- !is.na(coverage_table_idx)
      
      format_coverage$table[valid_table] <- name_map$tables$clean[
        coverage_table_idx[valid_table]
      ]
      
      valid_column <- !is.na(coverage_column_idx)
      format_coverage$variable[valid_column] <- name_map$columns$column_clean[
        coverage_column_idx[valid_column]
      ]
    }
  }
  
  
  overview <- data.frame(
    table = names(typed_tables),
    rows = vapply(typed_tables, nrow, integer(1)),
    columns = vapply(typed_tables, ncol, integer(1)),
    stringsAsFactors = FALSE
  )
  
  n_unmapped <- if (is.null(format_coverage)) {
    NA_integer_
  } else {
    sum(format_coverage$n_unmapped_codes > 0L)
  }
  
  summary <- c(
    n_tables = length(typed_tables),
    n_variables = nrow(metadata),
    n_type_conversion_problems = nrow(conversion$problems),
    n_format_assignments = if (is.null(format_map)) 0L else nrow(format_map),
    n_unmapped_format_variables = n_unmapped
  )
  
  if (verbose) {
    message(
      "Import completed: ",
      length(typed_tables),
      " tables, ",
      nrow(metadata),
      " variables."
    )
    
    total_rows <- sum(vapply(typed_tables, nrow, integer(1)))
    
    if (total_rows == 0L) {
      message("No data records found.")
    }
    
    if (nrow(conversion$problems) == 0L) {
      message("Type conversion: no problems detected.")
    } else {
      message(
        "Type conversion: ",
        nrow(conversion$problems),
        " variable(s) with conversion problems."
      )
    }
    
    if (apply_formats && !is.null(format_coverage)) {
      message(
        "SAS formats: ",
        sum(format_coverage$n_unmapped_codes > 0L),
        " variable(s) with unmapped codes."
      )
    }
    
    if (apply_formats && is.null(format_coverage)) {
      message("SAS format coverage: not available.")
    }
    
    if (clean_names) {
      message("Table and variable names were cleaned.")
    }
  }
  
  list(
    typed = typed_tables,
    display = display_tables,
    metadata = metadata,
    name_map = name_map,
    formats = list(
      assignments = format_map,
      values = format_values
    ),
    checks = list(
      overview = overview,
      conversion = conversion$all,
      format_coverage = format_coverage,
      summary = summary
    )
  )
}
